### PR TITLE
Some styles improvements

### PR DESCRIPTION
**Pull request by pmfx**
Added light bg color to fields, moved type dropdown to the left, removed
separator border for more clean look, adjusted icon size, added hover
effect to Icon select. Preview:
https://image.prntscr.com/image/IXmoM1FLQEC8dUW_Hn6GoQ.png

### CODE REVIEW

**Comment by mnoskov** [comment]
See what I get: http://take.ms/nP7Qk

1. Control icons lost their colors;
2. Control groups should not have borders, I think;
3. Also, control groups in nested fields should be on transparent background;
4. Instead trash (and minus) maybe better to use 'fa-times-circle'? (or instead of minus only)

**Comment by pmfx** [comment]
Hey @mnoskov First, thank you for this plugin. Love it!

1. I have removed controls icons colors on purpose to have more clean look. It's good ;) Maybe we can have "on hover" color change to red for "remove" though?
2. border is now changed to very light gray. Is it OK?
3. You're right, thats much better. Fixed.
4. Agree.

**Comment by mnoskov** [comment]
1. I think, icons must be colored, for better vizualization. May be dark colors initial, and bright on hover?

**Comment by pmfx** [comment]
Added hover colors. Green for insert and red for remove icon.

**Comment by mnoskov** [comment]
Good

**Comment by mnoskov** [comment]
Ready to merge?

**Comment by pmfx** [comment]
Yup, ready.

**Pull request merged**
