### PR TITLE
Update language

### PR DESCRIPTION
**Pull request by fourroses666**
#1

### CODE REVIEW

**Comment by fourroses666** [comment]
Hmm, I only added English to the README.md and nederland-UTF.php
Not sure why I see so many changed files.

I haven't played allot with Pull requests.

https://github.com/fourroses666/contentblocks/pull/1/files

**Comment by mnoskov** [comment]
It seems like develop branch from your fork merged with my develop branch

**Comment by mnoskov** [comment]
I will try to resolve this later

**Comment by mnoskov** [comment]
Sorry, but I have no idea what to do with it :)
You can try to fetch changes from master and to push request again, or I can make these changes manually, if you don't mind.

**Comment by mnoskov** [comment]
It will be better, if you create new file, README.eng.md e.g., for avoid collisions

**Comment by fourroses666** [comment]
Will try a new one!

**Pull request closed without merging**
